import numpy as np
import matplotlib.pyplot as plt

'''
the data is generated by adding noise to random y values of the reference line y= 2 + 0.8x 
'''
theta_0 = 2
theta_1 = 0.8
noise_var = 0.01

x = np.random.random((1, 20))[0]
ref_y = theta_0 + theta_1 * x
y = ref_y + np.sqrt(noise_var) * np.random.random((1, 20))[0]

data_points = [[i, j] for i, j in zip(x, y)]
print(data_points)

plt.figure(1)
plt.plot(x, y, 'go', label='Simple Linear Regression Data')
plt.axis('equal')
plt.legend(loc='lower right')
plt.show()
